[tool.pytest.ini_options]
python_files = ["test_*.py", "*_test.py", "test/unit/test_*.py"]
python_classes = ["Test"]
python_functions = ["test"]
testpaths = ["tests"]
addopts = [
    "--import-mode=importlib",
]
